#!/usr/bin/env bash
set -eo pipefail
export LC_ALL=C

SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)

TOUCH=touch
if command -v gtouch; then
    TOUCH=gtouch
fi

# Assumes you're in git top level dir
(
    cd src
    git ls-files | xargs -r "$TOUCH" --no-dereference --date="@${SOURCE_DATE_EPOCH}"
    
    # TODO append version?
    mkdir -p ../dist/
    git ls-files | zip -r -FS ../dist/'Just Detach Tab'.zip -@
)
