#!/bin/sh
set -eo pipefail
export LC_ALL=C

if ! command -v gh; then
    echo "GitHub CLI `gh' not found"
    exit 1
fi 

if [ -z "$1" ]; then
    echo "Needs a version"
    exit 1
fi

if ! git diff-index --quiet HEAD -- && [ -z "$FORCE_DIRTY_WORKTREE" ]; then
    echo "ERR: The current git worktree is dirty"
    exit 1
fi

read -p "About to create tag and release '$1', are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    gh release create "$1" dist/'Just Detach Tab.zip'
fi
